'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const MT=require('../public/core'),{prepare,callModel}=require('../lib/provider');
const photos=[{id:'a',title:'Cafe',caption:'Cafe with blue chairs',place:'Mumbai',scene:'cafe',color:'blue',tags:[]},{id:'b',title:'Cafe',caption:'Cafe with green plants',place:'Goa',scene:'cafe',color:'green',tags:[]},{id:'c',title:'Lake',caption:'Lake and mountains',place:'Manali',scene:'lake',tags:[]}];
test('uncertain place remains maybe',()=>{assert.equal(MT.parseDemo('A cafe with blue chairs, maybe Goa').find(c=>c.value==='goa').confidence,'maybe');});
test('matching certain visual clue outranks uncertain wrong city',()=>{const cs=MT.parseDemo('A cafe with blue chairs, maybe Goa');assert.equal(MT.rank(photos,'',cs)[0].id,'a');});
test('guesses do not remove unmatched photos',()=>{assert.equal(MT.rank(photos,'',MT.parseDemo('maybe Goa')).length,3);});
test('explicit rejection removes an item',()=>{assert.equal(MT.rank(photos,'',[],['a']).some(p=>p.id==='a'),false);});
test('ignored clue contributes no score',()=>{assert.equal(MT.rank(photos,'',[{value:'Goa',confidence:'ignore'}]).find(p=>p.id==='b').score,0);});
test('no known target does not fabricate correctness',()=>{assert.equal(MT.verifySelection('a',null).verified,null);});
test('wrong synthetic target is false success',()=>{assert.equal(MT.verifySelection('a','b').verified,false);});
test('correct synthetic target is verified',()=>{assert.equal(MT.verifySelection('a','a').verified,true);});
test('question derived from diverse available facets',()=>{assert.ok(MT.nextQuestion(photos,[]).options.length>=2);});
test('duplicate evidence text removed',()=>{const a={id:'a',text:'a source quote',source_url:'https://example.com/1'};assert.equal(MT.validateRecords([a,{...a,id:'b'}]).length,1);});
test('duplicate evidence IDs rejected',()=>{assert.throws(()=>MT.validateRecords([{id:'a',text:'text',source_url:'https://example.com'},{id:'a',text:'other',source_url:'https://example.com'}]));});
test('javascript provenance URLs rejected',()=>{assert.throws(()=>MT.validateRecords([{id:'a',text:'text',source_url:'javascript:alert(1)'}]));});
test('500-record import limit enforced',()=>{assert.throws(()=>MT.validateRecords(Array(501).fill({})));});
test('fabricated quote rejected',()=>{assert.throws(()=>MT.validateExtraction([{id:'a',quote:'invented',stage:'retrieve'}],[{id:'a',text:'real quote'}]));});
test('unknown source ID rejected',()=>{assert.throws(()=>MT.validateExtraction([{id:'b',quote:'real',stage:'retrieve'}],[{id:'a',text:'real'}]));});
test('valid quote preserves original URL and requires human review',()=>{const r=MT.validateExtraction([{id:'a',quote:'real',stage:'retrieve',summary:'possible miss'}],[{id:'a',text:'real quote',source_url:'https://example.com'}])[0];assert.equal(r.source_url,'https://example.com');assert.match(r.review_status,/human review pending/);});
test('discovery batch capped at 20',()=>{assert.throws(()=>prepare('discovery',{records:Array(21).fill({id:'a',text:'b'})}));});
test('unsupported image mime rejected',()=>{assert.throws(()=>prepare('caption',{mime:'text/html',data:'abcd'}));});
test('caption request uses inline image and schema',()=>{const r=prepare('caption',{mime:'image/jpeg',data:'YWJjZA=='});assert.ok(r.contents[0].parts[0].inlineData);assert.equal(r.generationConfig.responseMimeType,'application/json');});
test('ranking request bounds enforced',()=>{assert.throws(()=>prepare('rank',{photos:Array(33).fill({}),clues:[]}));});
test('unknown provider operation rejected',()=>{assert.throws(()=>prepare('execute',{}));});
test('provider JSON response parsed using a mock, not a live API',async()=>{const previous=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='MOCK_ONLY';try{const r=await callModel('parse',{query:'maybe Goa'},async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'{"clues":[]}' }]}}]})}));assert.deepEqual(r,{clues:[]});}finally{if(previous===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=previous;}});
